### ISSUE TITLE
sad

### ISSUE THREAD

**Issue by kai** [kaihj/hello#16]
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:

* Issue description must include reproduction steps [(?)](https://gitmagic.io/rules/#/issue/body-must-include-reproduction-steps)
* Issue title must start with uppercase [(?)](https://gitmagic.io/rules/#/issue/subject-must-start-with-case)
* Issue title must be in imperative, present tense \(e\.g\. "add", "fix", "change"\) [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-in-tense)
* Issue title must be longer than 4 characters [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-longer-than)

[Click here](https://app.gitmagic.io/kaihj/hello/16/134d7b65-abcc-4659-b3c2-8d89a250f767/b10efdd8-8385-47f0-8288-fe0cd0aee114) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>
